### PR TITLE
Bumped php-cs-fixer to v2.15 and added CS check job

### PR DESCRIPTION
**Pull request by alongosz**
|      |     |
| --- | --- |
| **Type** | Bug |
| **Target version** | `v1.0.2` for eZ Platform `v2.5.2 LTS` |

This PR:
- [x] bumps php-cs-fixer to v2.15.1 (locking `>=2.15.1 <2.16.0`),
- [x] adds composer cache directory to Travis cached directories,
- [x] adds a Travis job which checks code style ([failing build](https://travis-ci.org/ezsystems/ezplatform-rest/jobs/549685935), [passing build](https://travis-ci.org/ezsystems/ezplatform-graphql/builds/549706248?utm_source=github_status&utm_medium=notification)),
- [x] adds running Travis on stable branches (e.g. `1.0`),
- [x] disables unwanted CS rules,
- [x] fixes outstanding CS issues.

### CODE REVIEW

**Comment by alongosz** [comment]
> I think we should set `native_function_invocation` and `native_constant_invocation` to true if we do not overwrite many native function or constants.

We can discuss importance of native invocations as a follow up and apply them globally for all packages.

**Comment by mikadamczyk** [comment]
Maybe we should discuss disabling rules upfront

**Comment by mikadamczyk** [comment]
As we discussed in private we should change this in all repositories at once, because PR is huge already. Please, create follow-up ticket.

**Comment by alongosz** [comment]
> As we discussed in private we should change this in all repositories at once, because PR is huge already. Please, create follow-up ticket.

Created the [EZP-30694](https://jira.ez.no/browse/EZP-30694) Epic for this.

**Pull request merged**
