### PR TITLE
Allow to customize the root schema

### PR DESCRIPTION
**Pull request by bdunogier**
Makes the GraphQL container extension look for predefined files path in `app/config/graphql` that will be loaded instead of the Platform ones. It allows the app maintainer to add new items to the schema and handle custom business objects:

- `app/config/graphql/Query.types.yml` can define a `Query` type. It must inherit the `Domain` type.
- `app/config/graphql/Mutation.types.yml` can define a `Mutation` type. Once mutations are merged (#4), it will have to inherit the `DomainContentMutation` type.

See `doc/custom_app_schema.md` for examples.

### CODE REVIEW

**Comment by bdunogier** [comment]
@vfaisse after discussing this extension point internally, we believe that being able to add your own schema using the `overblog_graphql` configuration should be sufficient. Could you confirm that it is ? The only difference with that PR is that you need to use a different endpoint (e.g. `/graphql/custom`), and not integrate it into the ezplatform schema. Please let us know.

**Comment by bdunogier** [comment]
@webhdx CS fixed on the newly added files. The other files only have minor issues (phpdoc header, blank lines) that do not come from this particular PR. Maybe we can take care of them in master once this PR is merged (tomorrow if possible).

**Comment by vfaisse** [comment]
Hi @bdunogier, I confirm that I have successed to add my custom schema with overblog_graphql and a new endpoint as explained in the documenation.
Thank you Bertrand, and still good job for this bundle.

**Comment by bdunogier** [comment]
Thank you for the feedback, @vfaisse ! We have merged this PR nonetheless, since it contained other improvements. We may revert the commit that adds this specific extension point, but not immediately :-)

**Pull request merged**
