### PR TITLE
EZP-28034: Dropped unused imports from SearchQueryMapperSpec

### PR DESCRIPTION
**Pull request by ViniTou**

### CODE REVIEW

**Comment by ViniTou** [comment]
It seems that REST class was here by mistake and it was not used in test.

**Comment by lserwatka** [comment]
@ViniTou does it affect 1.0 branch?

**Comment by alongosz** [comment]
> @ViniTou does it affect 1.0 branch?

That's a good point, it was incorrect on 1.0 already. @ViniTou could you rebase?

**Comment by ViniTou** [comment]
@alongosz 
@lserwatka 
rebased and target changed to `1.0`

**Comment by alongosz** [comment]
Thanks. CI passes and this is too straightforward to spend QA on it, so - merging :tada:

**Pull request merged**
